
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jaitheking
 */
public class AR_GUI extends javax.swing.JFrame {
    private  Connection conn = null;
    private  PreparedStatement pst = null;
    private ResultSet rs = null;
    private String total_student;
    
    public AR_GUI() {
        initComponents();
        student_register.setText(get_number_registered_student());
        student_register.setEditable(false);
        popular_title.setText(get_most_popular_title());
        popular_title.setEditable(false);
        popular_title.setLineWrap(true);
        popular_title.setWrapStyleWord(true);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        student_register_lbl = new javax.swing.JLabel();
        popular_lbl = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        student_register = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        popular_title = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        student_register_lbl.setText("Total Number of Students Registered:");

        popular_lbl.setText("Most Popular Subject:");

        lbl_title.setFont(new java.awt.Font("Droid Sans", 1, 24)); // NOI18N
        lbl_title.setText("Analysis Report of MMU BOARD");

        jButton1.setText("CLOSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        student_register.setBackground(new java.awt.Color(62, 212, 226));
        student_register.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        student_register.setText("jTextField1");
        student_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_registerActionPerformed(evt);
            }
        });

        popular_title.setBackground(new java.awt.Color(62, 212, 226));
        popular_title.setColumns(20);
        popular_title.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        popular_title.setRows(5);
        jScrollPane1.setViewportView(popular_title);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(student_register_lbl)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(popular_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(student_register, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_title)
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbl_title)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(student_register_lbl)
                            .addComponent(student_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addComponent(popular_lbl)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void student_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_registerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_registerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public final String get_number_registered_student(){
            
         conn=DB_Controller.ConnectDB();
        String Sql = "SELECT COUNT(user_id) AS Total_Student FROM  user WHERE  user_type = ?";
        
        try{
            pst=conn.prepareStatement(Sql);
            
            pst.setString(1,"Student");
            rs = pst.executeQuery();
            if(rs.next()){
               total_student = rs.getString("Total_Student");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        return total_student;
    }
    public final String get_most_popular_title(){
        String s1 = null,s2 = null;
        conn=DB_Controller.ConnectDB();
        String Sql = "SELECT subject_name, title_name, COUNT( * ) AS Total FROM subject_title INNER JOIN title_comment ON subject_title.id = title_comment.title_id GROUP BY title_comment.title_id ORDER BY Total DESC LIMIT 0 , 1";
        
        try{
            pst=conn.prepareStatement(Sql);
            
            
            rs = pst.executeQuery();
            if(rs.next()){
               s1 = rs.getString("subject_name");
               s2 = rs.getString("title_name");
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        String result = s1+" - "+s2;
        return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel popular_lbl;
    private javax.swing.JTextArea popular_title;
    private javax.swing.JTextField student_register;
    private javax.swing.JLabel student_register_lbl;
    // End of variables declaration//GEN-END:variables
}
